### PR TITLE
updates background logic

### PR DESCRIPTION
**Pull request by bulbil**
@stephenwf thanks for your ideas on Slack last week -- I'm hoping this doesn't preclude some functionality you had in mind, but after going over the issue, I realized I would prefer to avoid thinking of the background as a prop at all. Instead, I opted to calculate it based on the css custom prop `--atlas-background` exclusively. 

Will this work for you?

### CODE REVIEW

**Comment by bulbil** [comment]
One question is about `static-renderer.ts` options -- I wasn't super clear on why set the background in the renderer and whether there were any issues with my removing the prop from the parent.

[background: '#000',](https://github.com/bulbil/atlas/blob/d1fbccaab4430c4ed04da33eb60378f5b97c7e87/src/modules/static-renderer/static-renderer.ts#L46-L47)

**Comment by bulbil** [comment]
@stephenwf apologies, I was distracted by a few other tasks around here. I went ahead and re-added the background prop to atlas. As per your Slack comment, I believe the current cascade for determining background: 1) custom css prop 2) background prop 3) default (`#000`)

**Review by stephenwf — APPROVED** [review]

**Comment by stephenwf** [comment]
Looks and work well! Do you want this released on the 2.1.x branch too so it can be ported to Canvas Panel?

**Comment by abrin** [comment]
@stephenwf if it's ok to push this through to a CanvasPanel release, that would be amazing, thank you!

**Comment by bulbil** [comment]
> Looks and work well! Do you want this released on the 2.1.x branch too so it can be ported to Canvas Panel?

@stephenwf actually reading your comment more closely I realize I wasn't sure if you were purposefully keeping certain updates out of Canvas Panel. Does `atlas@2.2.x` introduce breaking changes?

**Pull request merged**
